source 'https://rubygems.org'

gem 'bcrypt'
gem 'bigdecimal', force_ruby_platform: true
gem 'escape_utils'
gem 'eventmachine', force_ruby_platform: true
gem 'fast-stemmer'
gem 'ffi', force_ruby_platform: true
gem 'fiddle', force_ruby_platform: true
gem 'hitimes'
gem 'json'
gem 'mini_portile2'
gem 'mysql2', force_ruby_platform: true
gem 'pact_broker-client'
gem 'pg', force_ruby_platform: true
gem 'psych', force_ruby_platform: true
gem 'puma', force_ruby_platform: true
gem 'RedCloth'
gem 'redcarpet'
gem 'rexml'
gem 'rinda'
gem 'stringio', force_ruby_platform: true
gem 'test-unit'
gem 'thruster', force_ruby_platform: true, require: false
gem 'thin', force_ruby_platform: true
gem 'unf_ext', force_ruby_platform: true
gem 'webrick'
gem 'yajl-ruby'

# ## WIP - Windows ARM

gem "sqlite3", force_ruby_platform: true
gem 'nokogiri', force_ruby_platform: true
# gem 'pact_broker'
# gem 'rails'

# # wont build on windows arm

gem 'curses', force_ruby_platform: true
gem 'rugged', force_ruby_platform: true


## Not supported on Windows
# unicorn requires charlock_holmes & kgio
# no support on windows (no mmap /getaddrinfo) pitchfork is a maintained fork
gem 'unicorn', force_ruby_platform: true unless Gem.win_platform?
gem 'charlock_holmes', force_ruby_platform: true unless Gem.win_platform?
gem 'kgio', force_ruby_platform: true unless Gem.win_platform?
gem 'raindrops', force_ruby_platform: true unless Gem.win_platform?
gem 'pitchfork', force_ruby_platform: true unless Gem.win_platform?

# ## End WIP - Windows ARM
# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.1"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
# gem "sqlite3", ">= 2.1"
# Use the Puma web server [https://github.com/puma/puma]
# gem "puma", ">= 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
# gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem "bundler-audit", require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end
