name: Alpine linux-musl - x86_64 - build from dockerhub builder

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

env:
  PKG_DATE: 20260608

jobs:
  setup-ruby-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.ruby_versions }}
    steps:
      - name: Set Ruby versions
        id: set-versions
        run: |
          if [[ "${GITHUB_REF}" == *preview* || "${GITHUB_HEAD_REF}" == *preview* || "${GITHUB_REF_NAME}" == *preview* ]]; then
            echo "ruby_versions=['3.5.0-preview1','4.0.0-preview2']" >> $GITHUB_OUTPUT
          else
            echo "ruby_versions=['4.0.7']" >> $GITHUB_OUTPUT
          fi

  make-linux-musl-x86_64:
    needs: [ setup-ruby-versions ]
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: ${{ fromJson(needs.setup-ruby-versions.outputs.versions) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@master
        with:
            ruby-version: ${{ matrix.ruby-version }}
      - name: package
        run: |
            cd linux-musl
            rake
            rake package_full
            ls
        env:
          ARCHITECTURES: "x86_64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      - name: package gems
        run: ./scripts/package-gems.sh    
        env:
          PLATFORM: linux-musl
      - name: 'Upload Artifact - linux x86_64'
        uses: actions/upload-artifact@v5
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-linux-musl-x86_64.tar.gz
          path: linux-musl/traveling-ruby*.tar.gz
      - name: test
        run: |
            cd linux-musl
            rake test_docker
        env:
          ARCHITECTURES: "x86_64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}

      - name: Publish archives and packages
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: 'Release ${{ github.event.release.tag_name }}'
          generate_release_notes: true
          body: ${{ github.event.release.body }}
          files: linux-musl/traveling-ruby-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}