name: Windows-via-unix
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # release:
  #   types: [published]

env:
  PKG_DATE: 20260922

jobs:
  build-windows:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, x86]
        ruby-version: [4.0.7]
        include:
          - arch: arm64
            ruby-version: 4.0.7
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: package ${{ matrix.arch }}
        run: |
          uname -m
          cd windows
          brew install 7zip
          rake
          ls
        env:
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
          ARCHITECTURES: ${{ matrix.arch }}
      - name: "Upload Artifact - traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-windows-${{ matrix.arch }}"
        uses: actions/upload-artifact@v5
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-windows-${{ matrix.arch }}.tar.gz
          path: windows/traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-windows-${{ matrix.arch }}.tar.gz

      - name: Publish archives and packages
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: 'Release ${{ github.event.release.tag_name }}'
          generate_release_notes: true
          body: ${{ github.event.release.body }}
          files: windows/traveling-ruby-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-windows:
    needs: build-windows
    strategy:
      matrix:
        arch: [x86_64]
        ruby-version: [4.0.7]
        os: [windows-latest]
        include:
          - os: windows-11-arm
            arch: arm64
            ruby-version: 4.0.7
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: "Download Artifact"
        uses: actions/download-artifact@v5
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-windows-${{ matrix.arch }}.tar.gz
          path: windows/
      - name: "Test binary"
        working-directory: windows
        shell: bash
        run: |
          mkdir output
          tar xzf traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-windows-${{ matrix.arch }}.tar.gz -C output
          ../shared/test-gems.sh -p windows -a ${{ matrix.arch }} output
        env:
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
          ARCHITECTURES: ${{ matrix.arch }}
